services:
  opencode:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1010
        GID: 100
    container_name: opencode
    volumes:
      - ./opencode.json:/home/levente/.config/opencode/opencode.json:ro
      - /home/levente/config:/home/levente/config
      - /home/levente/Documents:/home/levente/Documents
    environment:
      - OPENCODE_CONFIG=/home/levente/.config/opencode/opencode.json
    ports:
      - "4096:4096"
    stdin_open: true 
    tty: true   
    networks:
      - vibe_sandbox


networks:
  vibe_sandbox:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false" # Isolates container from your local network
      
